### ISSUE TITLE
Promise based api?

### ISSUE THREAD

**Issue by aidenybai** [towerofnix/scratch-new-api#1]
I feel like when writing with this api it feels weird, wouldn't it be easier to write it promise based?

**Comment by towerofnix** [comment]
It actually is all promise-based - I just use async/await in my examples because I personally find them easier to work with. (Also, async generators - that unusual `for await (...)` syntax you see - are basically necessary in order to support streaming data from the API.)

What sort of changes would you suggest? If you were writing an imaginary API library in your head, what would code using it look like (roughly)?

While I'm not prioritizing work on this library personally, I'm open to figuring out how to make its syntax cleaner where possible...personally, I dislike that you have to do `await project.getTitle()` to get a project's title - it would be nicer if you could do the ordinary `project.title`, and therefore do destructuring like `const {title, stats} = project`. But I'm not sure exactly how to implement that, since data isn't guaranteed to be present, per se. Anyway, that's sort of an aside - could you clarify what you meant by making the library more promise-based?

**Comment by aidenybai** [comment]
Thank you for the quick reply -

It's more of a personal preference for me, as most of the wrappers of APIs i've worked with use this method, I'm visualizing it to be something like: 
`project.getTitle('foo').then(project => do something);`

I feel like this would be easier as the promise only fulfills when it receives status code 200, or rej for anything else. 

I'm not too familiar with node-fetch, but here's my thought process on the implementation:
1. return promise fetching the endpoint
2. switch/case for status codes, rej on error, res if found

**Comment by towerofnix** [comment]
I see - you can actually do exactly that sort of syntax with this library. This is also valid code with the library:

```js
const scratch = new Scratch();
const project = scratch.getProject({id: 276660597});
project.getTitle().then(title => {
    // do something
});
```

The `node-fetch` module I use is just a Node.js implementation of the browser-standard [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

I haven't explicitly looked into error handling yet, but eventually it will raise rejections if there is an error (e.g. if a user with the given username is not found). Those will be catchable with `.catch()` if you're working directly with the promises, or via a `try {} catch {}` block if you're using async/await.

**Comment by aidenybai** [comment]
Ah, I realize my mistake now. Thanks for the FYI!

**Comment by towerofnix** [comment]
No worries, glad to clarify!
